project:
  type: website

website:
  search:
    location: navbar
    type: overlay
  favicon: images/Joaquin.jpg
  title: "Portfolio"
  navbar:
    left:  
      - href: index.qmd
        text: Home
      - href: research.qmd
        text: "Research & Fellowships"
      - href: experience.qmd
        text: Work Experience
      - href: projects.qmd
        text: Class Projects
      - href: personal.qmd
        text: Personal Projects
      - href: blog.qmd
        text: Blog
    right:
      - icon: github
        href: https://github.com/jgonzalezsalgado
        target: _blank
      - icon: linkedin
        href: https://www.linkedin.com/in/joaquin-e-gs/
        target: _blank  


format:
  html:
    theme:
      light:
      - cosmo
      - brand
      dark: darkly
    css: styles.css
    toc: true
    
