project:
  type: website

website:
  search:
    location: navbar
    type: overlay
  favicon: images/Joaquin.jpg
  title: "Portfolio"
  navbar:
    logo: images/logo.png
    logo-herf: https://github.com/jgonzalezsalgado 
    left:
      - href: index.qmd
        text: Home
      - href: research.qmd
        text: Research & Fellowships
      - href: experience.qmd
        text: Work Experience
      - href: projects.qmd
        text: Personal & Class Projects
      - href: blog.qmd
        text: Blog


format:
  html:
    theme:
      light:
      - cosmo
      - brand
      dark: darkly
    css: styles.css
    toc: true
    
