project:
  type: website

website:
  title: "Portfolio"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: index.qmd#research
        text: Research & Fellowships
      - href: index.qmd#experience
        text: Experience
      - href: index.qmd#projects
        text: Projects
      - href: index.qmd#contact
        text: Contact Me

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
